### ISSUE TITLE
ReadDirectory BSOD

### ISSUE THREAD

**Issue by vasama** [winfsp/winfsp#565] opened 2024-07-07 18:10 UTC
## Bug Report

BSOD caused by ReadDirectory. Looking at `FspFsvolQueryDirectoryCopy`, I'm not seeing any input validation of `NextOffset`, though perhaps I'm just missing it.

### How to Reproduce

Possibly by writing garbage into `FSP_FSCTL_DIR_INFO::NextOffset` in `ReadDirectory`.

### Environment

- OS version and build: Windows 10 (10.0.19045)
- WinFsp version and build: Both 2023 and 2024B1

### Attached dump files

The zip contains two dump files. One for each version I tested. I've emailed the zip password to you at [billziss@navimatics.com](mailto:billziss@navimatics.com).

[winfsp-bsod-dump.zip](https://github.com/user-attachments/files/16120224/winfsp-bsod-dump.zip)

**Comment by billziss-gh** [comment] 2024-07-07 21:09
Thank you. I am currently on vacation and may not be able to check this in a timely manner.

**Comment by vasama** [comment] 2024-07-10 06:27
> Thank you. I am currently on vacation and may not be able to check this in a timely manner.

That's fine by me. Changing my user mode code to behave better fixed it for me.

**Comment by billziss-gh** [comment] 2024-07-10 14:03
Understood.

However because no application should be able to use WinFsp to crash Windows, I intend to fix this problem once I am back from vacation.

**Comment by vasama** [comment] 2024-07-10 16:31
> Understood.
> 
> However because no application should be able to use WinFsp to crash Windows, I intend to fix this problem once I am back from vacation. 

Oh absolutely. That's why I reported it. 🙂

**Comment by billziss-gh** [comment] 2024-08-21 09:51
@vasama 

I am looking at this problem now and I think I may have found what the issue is. Do you happen to have a reliable repro so that I can test?

(The problem does not appear to be related to `NextOffset`.)

**Comment by vasama** [comment] 2024-08-21 10:01
Unfortunately I don't have the history for the code in question at the point where it crashed. I can see if I can reproduce it though. I seem to recall it went away when I zeroed `NextOffset`, but there may have been more to it.

**Comment by billziss-gh** [comment] 2024-08-21 10:13
Thank you. Reproducing it would be very helpful to ensure that the problem has been correctly identified and that the fix is adequate.

FYI, the problem does not seem to be directly related to `NextOffset`, but perhaps when you zero it out there may be some other "beneficial" effect.

**Comment by billziss-gh** [comment] 2024-08-21 10:34
I have pushed a potential fix in the private branch [`pvt-dirfix`](https://github.com/winfsp/winfsp/tree/pvt-dirfix). Please keep in mind that I am not 100% convinced that this is the correct fix, as the check added in the commit guards against a condition that "should never happen".

**Comment by vasama** [comment] 2024-08-22 10:37
Unfortunately I was not able to reproduce the crash. I had a look at the dump too, and I see where you're going with the fix. I don't fully grok the driver, especially since I have no experience with kernel development, but I agree that this just looks like a bandaid that doesn't address the real issue. Somehow either the `DirInfoCacheHint` has been corrupted (seems unlikely) or the data in the cache has been swapped out without resetting the hint.

**Comment by billziss-gh** [comment] 2024-08-22 12:53
Understood. I would hold off on this fix then as we cannot be certain that it fixes the real problem. Please let me know if the problem materializes again.

**Comment by billziss-gh** [comment] 2024-09-13 12:29
I am closing this for now, but please reopen if you are able to reproduce the problem.

**Closed by billziss-gh** 2024-09-13 12:29 UTC
