### ISSUE TITLE
BSOD on CcDeferWrite by FspFsvolWriteCached. (IRQL_NOT_LESS_OR_EQUAL)

### ISSUE THREAD

**Issue by jgh0721** [winfsp/winfsp#470] opened 2022-11-23 08:44 UTC
iMonFSP => WinFSP( only rename, without any modification )

```
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

IRQL_NOT_LESS_OR_EQUAL (a)
An attempt was made to access a pageable (or completely invalid) address at an
interrupt request level (IRQL) that is too high.  This is usually
caused by drivers using improper addresses.
If a kernel debugger is available get the stack backtrace.
Arguments:
Arg1: 0000000000000450, memory referenced
Arg2: 0000000000000002, IRQL
Arg3: 0000000000000000, bitfield :
	bit 0 : value 0 = read operation, 1 = write operation
	bit 3 : value 0 = not an execute operation, 1 = execute operation (only on chips which support this level of status)
Arg4: fffff8041b3a28b0, address which referenced memory

Debugging Details:
------------------


KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 1655

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 27259

    Key  : Analysis.IO.Other.Mb
    Value: 266

    Key  : Analysis.IO.Read.Mb
    Value: 5

    Key  : Analysis.IO.Write.Mb
    Value: 149

    Key  : Analysis.Init.CPU.mSec
    Value: 446608

    Key  : Analysis.Init.Elapsed.mSec
    Value: 4426546

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 220

    Key  : Bugcheck.Code.DumpHeader
    Value: 0xa

    Key  : Bugcheck.Code.KiBugCheckData
    Value: 0xa

    Key  : Bugcheck.Code.Register
    Value: 0x3

    Key  : WER.OS.Branch
    Value: ni_release

    Key  : WER.OS.Timestamp
    Value: 2022-05-06T12:50:00Z

    Key  : WER.OS.Version
    Value: 10.0.22621.1


BUGCHECK_CODE:  a

BUGCHECK_P1: 450

BUGCHECK_P2: 2

BUGCHECK_P3: 0

BUGCHECK_P4: fffff8041b3a28b0

READ_ADDRESS:  0000000000000450 

PROCESS_NAME:  System

TRAP_FRAME:  ffffa40ae9702570 -- (.trap 0xffffa40ae9702570)
NOTE: The trap frame does not contain all registers.
Some register values may be zeroed or incorrect.
rax=0000000000000000 rbx=0000000000000000 rcx=ffffce8fd3aa0bd0
rdx=ffffce8fd3aa0bd0 rsi=0000000000000000 rdi=0000000000000000
rip=fffff8041b3a28b0 rsp=ffffa40ae9702700 rbp=0000000000000000
 r8=0000000000000000  r9=0000000077446343 r10=fffff8041bcf7f40
r11=00000000ffffffff r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei ng nz na po nc
nt!CcPostDeferredWrites+0x48:
fffff804`1b3a28b0 498b3f          mov     rdi,qword ptr [r15] ds:00000000`00000000=????????????????
Resetting default scope

STACK_TEXT:  
ffffa40a`e9701c18 fffff804`1b5587c2     : ffffa40a`e9701d80 fffff804`1b389380 ffff9380`20f6a180 00000000`00000401 : nt!DbgBreakPointWithStatus
ffffa40a`e9701c20 fffff804`1b557eb3     : ffff9380`00000003 ffffa40a`e9701d80 fffff804`1b441780 ffffa40a`e9702330 : nt!KiBugCheckDebugBreak+0x12
ffffa40a`e9701c80 fffff804`1b4284c7     : ffffa40a`e9702490 fffff804`1b4bc7fc 00000000`00000000 00000000`00000003 : nt!KeBugCheck2+0xba3
ffffa40a`e97023f0 fffff804`1b43daa9     : 00000000`0000000a 00000000`00000450 00000000`00000002 00000000`00000000 : nt!KeBugCheckEx+0x107
ffffa40a`e9702430 fffff804`1b439134     : 00000000`000007fa ffffce8f`dc364030 00000000`00000000 00000000`00000000 : nt!KiBugCheckDispatch+0x69
ffffa40a`e9702570 fffff804`1b3a28b0     : 00000000`00000000 00000000`00000000 fffff804`19eae940 ffffce8f`dc04d058 : nt!KiPageFault+0x474
ffffa40a`e9702700 fffff804`1b5279a1     : ffffce8f`00000000 ffffce8f`d3aa0710 ffffa40a`e97027c0 00000000`00000000 : nt!CcPostDeferredWrites+0x48
ffffa40a`e9702770 fffff804`19eaf7b9     : ffffce8f`db97a7d0 fffff804`19e57d50 ffffce8f`da553040 00000000`00000000 : nt!CcDeferWrite+0x1e1
ffffa40a`e9702800 fffff804`19eaea13     : ffffce8f`db59f730 ffffce8f`dbf07370 ffffce8f`dbf07440 fffff804`1b215801 : imonfsp_x64!FspFsvolWriteCached+0x249 [D:\Dev\iMonFTSv2\iMonFSP\src\sys\write.c @ 262] 
ffffa40a`e9702950 fffff804`1b214f95     : ffffce8f`dbf07370 ffffce8f`00000000 ffffa40a`00000000 ffffce8f`00000000 : imonfsp_x64!FspWqWorkRoutine+0xd3 [D:\Dev\iMonFTSv2\iMonFSP\src\sys\wq.c @ 152] 
ffffa40a`e9702a00 fffff804`1b3088b7     : ffffce8f`da553040 00000000`0000018c ffffce8f`da553040 fffff804`1b214e40 : nt!ExpWorkerThread+0x155
ffffa40a`e9702bf0 fffff804`1b42d324     : fffff804`16395180 ffffce8f`da553040 fffff804`1b308860 00000000`00000000 : nt!PspSystemThreadStartup+0x57
ffffa40a`e9702c40 00000000`00000000     : ffffa40a`e9703000 ffffa40a`e96fd000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x34


FAULTING_SOURCE_LINE:  D:\Dev\iMonFTSv2\iMonFSP\src\sys\write.c

FAULTING_SOURCE_FILE:  D:\Dev\iMonFTSv2\iMonFSP\src\sys\write.c

FAULTING_SOURCE_LINE_NUMBER:  262

FAULTING_SOURCE_CODE:  
   258:         {
   259:             IoMarkIrpPending(Irp);
   260:             CcDeferWrite(FileObject, FspFsvolWriteCachedDeferred, Irp, 0, WriteLength, Retrying);
   261: 
>  262:             return STATUS_PENDING;
   263:         }
   264: 
   265:         /* if we are unable to defer we will go ahead and (try to) service the IRP now! */
   266:     }
   267: 


SYMBOL_NAME:  imonfsp_x64!FspFsvolWriteCached+249

MODULE_NAME: imonfsp_x64

IMAGE_NAME:  imonfsp-x64.sys

STACK_COMMAND:  .cxr; .ecxr ; kb

BUCKET_ID_FUNC_OFFSET:  249

FAILURE_BUCKET_ID:  AV_imonfsp_x64!FspFsvolWriteCached

OS_VERSION:  10.0.22621.1

BUILDLAB_STR:  ni_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {e8eb410c-daa4-3535-b39c-50217e45e58c}

Followup:     MachineOwner
---------

3: kd> !irp 0xffffce8fdbf07370
Irp is active with 2 stacks 1 is current (= 0xffffce8fdbf07440)
 Mdl=ffffce8fdc30ed20: No System Buffer: Thread ffffce8fdad59080:  Irp stack trace.  
     cmd  flg cl Device   File     Completion-Context
>[IRP_MJ_WRITE(4), N/A(0)]
            0 e1 ffffce8fdb59f730 ffffce8fdb97a7d0 fffff8041c7f2e40-ffffce8fdc3c3aa0 Success Error Cancel pending
	       \FileSystem\iMonFSP	FLTMGR!FltpSynchronizedOperationCompletion
			Args: 00001000 00000000 00000000 00000000
 [IRP_MJ_WRITE(4), N/A(0)]
            0  0 ffffce8fdadd7060 ffffce8fdb97a7d0 00000000-00000000    
	       \FileSystem\FltMgr
			Args: 00001000 00000000 00000000 00000000
```

----------------

Symptom: Occurs intermittently when recording a 500mb file.

There are drives C and D, and drive D is a virtual area created with WinFSP.

About 500mb in C drive is opened intermittently when I open a file and write the contents to D drive with fwrite function.

-----

Attached File is dump 

https://workupload.com/archive/gd4dBEH3

**Comment by jgh0721** [comment] 2022-11-23 08:59
The original file is opened as a Memory Mapped File and is about 500Mb.
The target file is opened with _wfopen and written with fwrite three times: 1024 bytes, 7168 bytes, and all the rest.

**Comment by billziss-gh** [comment] 2022-11-23 12:54
For me to accept and investigate a BSOD you must be able to demonstrate it against the **official** WinFsp release and without any third party drivers in the system.

Some of my reasons for this:

- If the problem is not against the official release I cannot be certain that there have been no modifications (including unintentional ones).

- I lack full symbols to properly research the memory dump.

- The problem is often with a third party driver (as was the case in your previous BSOD report against WinFsp).

**Comment by billziss-gh** [comment] 2022-11-24 12:27
I am closing this, but please reopen if you can demonstrate the same problem against the official WinFsp releases and without any third party drivers affecting operation.

**Closed by billziss-gh** 2022-11-24 12:27 UTC
