### ISSUE TITLE
Service class call back for param change

### ISSUE THREAD

**Issue by deepanshug** [winfsp/winfsp#443] opened 2022-09-13 04:39 UTC
I am very to windows services and have some requirement where I need to handle a callback where parameters of a service changes.
i.e. for SERVICE_ACCEPT_PARAMCHANGE.

I could see there are only two callbacks handled for start and stop. Is there any plan to implement for prama change.
Please guide me if its already there.

**Comment by billziss-gh** [comment] 2022-09-13 08:01
Use `FspServiceRunEx` and its `OnControl` parameter.

**Comment by deepanshug** [comment] 2022-09-15 08:38
Hi Thanks for your response.

One more question, as soon as my service stops, it unmounts the directory but does not close the file opened from mount point. I don't know the file type or the process it will start, its all decided at run time so can't use process kill either.

Can you suggest further on this.

Thanks
Deepanshu
________________________________

**Comment by billziss-gh** [comment] 2022-09-15 11:14
> One more question, as soon as my service stops, it unmounts the directory but does not close the file opened from mount point. I don't know the file type or the process it will start, its all decided at run time so can't use process kill either.

I am not sure what your question is.

If you are saying that a process can keep files open on a file system that is already unmounted this is by design on Windows. The file handles will remain around for as long as the process wishes. They will be non-functional (any operation on them except `CloseHandle` will fail with `ERROR_OPERATION_ABORTED`), but they will remain open.

You can kill those processes if you wish, although I would advise against it: When a file system receives an open request it also receives information about the PID of the process that opened the file (`FspFileSystemOperationProcessId`).

In any case I am closing this issue as the original question has been addressed.

**Closed by billziss-gh** 2022-09-15 11:14 UTC

**Comment by deepanshug** [comment] 2022-09-15 13:03
Thank you very much again for your response.
You have answered both my questions and yes issue should be closed.

Thanks again for taking time to explain.

Regards
Deepanshu
________________________________
