### ISSUE TITLE
Save text file from Notepad not working on Windows 11 after installing latest windows updates.

### ISSUE THREAD

**Issue by d-s-qubeslab** [winfsp/winfsp#573] opened 2024-08-12 05:55 UTC
## Bug Report

Save text file from Notepad not working on Windows 11
The issue started on 9th August 2024 (Indian Standard Time), it was working well till 8th August.
The difference I noticed between the two days is the installation of Windows update:  Update for Microsoft Defender Antivirus - KB2267602 (Version 1.417.27.0) - Current Channel (Broad)

Notepad++ and other applications are able to save text file properly, only observed the issue with Notepad.

Passthrough sample has this defect.

### How to Reproduce

1. Run passthrough sample
2. Open a text file (say a.txt) in Notepad, edit the file, save the file. 
3. Instead of saving the file, the "Save as" dialog opens. 
4. If you click "Save" in "Save as" dialog, it shows error message "a.txt already exists, Do you want to replace it?"
5. If you select "Yes" you get the error "The volume does not contain a recognized file system. Please make sure that all required file system drivers are loaded and that the volume is not corrupted."
6. Save fails.

### Behaviors

The Save was working with the same code until 8th August, the issue is likely triggered by Windows update.

### Environment

- Os: Windows 11 Home Single Language
- OS version and build: 23H2 22631.3958
- WinFsp version and build: 2.0.23075
- Processor: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
- RAM: 16 GB

**Comment by d-s-qubeslab** [comment] 2024-08-13 07:03
Video of the defect:
https://github.com/user-attachments/assets/71d9a23c-ae0e-4079-bc83-75e0b15087c1

**Comment by billziss-gh** [comment] 2024-08-16 12:55
Does this issue exist with MEMFS or NTPTFS?

**Comment by d-s-qubeslab** [comment] 2024-08-19 07:58
Thanks for the response Bill, 

Yes, MEMFS has the same issue. 

Please see the video.

[https://github.com/user-attachments/assets/a786230e-80f5-432d-aa1b-678164722c2a](https://github.com/user-attachments/assets/a786230e-80f5-432d-aa1b-678164722c2a)

**Comment by d-s-qubeslab** [comment] 2024-08-19 08:10
[not_working_win11_save_notepad.spy.txt](https://github.com/user-attachments/files/16657519/not_working_win11_save_notepad.spy.txt)
File Spy log with passthrough - error case.

**Comment by billziss-gh** [comment] 2024-08-19 09:40
Microsoft seems to have a list of Defender updates [here](https://learn.microsoft.com/en-us/defender-endpoint/microsoft-defender-antivirus-updates#monthly-platform-and-engine-versions). The relevant update seems to be the [July](https://learn.microsoft.com/en-us/defender-endpoint/microsoft-defender-antivirus-updates#july-2024-platform-418240705--engine-11240703) one (release on August 7), though the version numbers slightly mismatch.

Are there any events logged in the Event Viewer when this problem happens?

**Comment by d-s-qubeslab** [comment] 2024-08-19 10:03
Couldn't find any events logged in the Event Viewer when this issue happens.

**Comment by d-s-qubeslab** [comment] 2024-08-19 13:16
Same error.

https://github.com/user-attachments/assets/44d6450e-0e46-4e6c-9b48-39bd13e5fd3a

**Comment by d-s-qubeslab** [comment] 2024-08-19 13:29
MEMFS FileSpy log (With -F NTFS parameter)
[memfs_ntfs2.spy.txt](https://github.com/user-attachments/files/16660803/memfs_ntfs2.spy.txt)

**Comment by billziss-gh** [comment] 2024-08-21 08:53
The new log also contains no mention of `STATUS_UNRECOGNIZED_VOLUME`.

This makes it much harder to troubleshoot this problem. I would have to reproduce the problem under a kernel debugger and then figure out what (non-WinFsp) component is returning the `STATUS_UNRECOGNIZED_VOLUME` error code and why.

A couple of things I noticed in the log:

- Explorer keeps sending `IOCTL_MOUNTDEV_QUERY_DEVICE_NAME`, which is a Mount Manager IOCTL.
- Explorer keeps sending `FSCTL_CREATE_OR_GET_OBJECT_ID`, which is an IOCTL used to manage a file's object ID. Not all file systems support object ID's for files: for example, Microsoft's ReFS does not and WinFsp does not.

A couple of more experiments to try:

- Mount MEMFS via the Mount Manager. This creates a global drive that is available to all accounts and you will need to be Administrator to do it. Use a command line like: `memfs-x64 -m \\.\X: -F NTFS`.
- Mount MEMFS as a network drive. Use a command line like `memfs-x64 -u \memfs\share -m X:`. (I expect this to not have any problems).

And a question: do you have any special Windows or Windows Defender configuration on the system(s) that exhibit this problem?

**Comment by billziss-gh** [comment] 2024-08-22 13:23
@d-s-qubeslab thank you for your help with the troubleshooting.

The fact that it works when mounting via the Mount Manager or as a network drive is very informative. It suggests that the problem is not with the file system per se, but with the method that is used to mount the file system.

WinFsp can mount file systems in a variety of ways. For our discussion the following mounting methods are relevant:

1. As a local "disk" drive, which uses the `DefineDosDevice` API. These drives are visible only to the account that created them, unless they are created by the `SYSTEM` account in which case they are visible to all accounts.

2. As a global "disk" drive via the Mount Manager. These drives are visible to all accounts and they are also recorded in the Mount Manager "database".

3. As a "network" drive, which goes via the [MUP](https://learn.microsoft.com/en-us/windows-hardware/drivers/ifs/support-for-unc-naming-and-mup). These drives are created using `DefineDosDevice` and are local to the account that created them, but they are also special in that the mounted file system is part of the UNC namespace.

Since this works with mounting methods 2 and 3, but not method 1, it would be good to try the following test using the [`subst`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/subst) utility, which also uses `DefineDosDevice` to create drives (I believe).

Create a drive using the `subst` with a drive that points to an NTFS directory and try your Notepad scenario on it. The command line would like something like (untested): `subst X: C:\TestDir`.

**Comment by d-s-qubeslab** [comment] 2024-08-23 06:54
@billziss-gh thanks.

Created X: with command `subst X: D:\temp2`, No issues, Save from Notepad works well in X:
Tested original issue again with command `memfs-x64 -m M: -F NTFS`, the issue is there as expected.

**Comment by billziss-gh** [comment] 2024-08-23 09:01
@d-s-qubeslab understood. Thank you for your investigation so far.

**Comment by billziss-gh** [comment] 2024-08-23 13:41
I installed latest version of Windows 11 on a kernel debuggable VM. Unfortunately I am unable to reproduce this.

<img width="642" alt="image" src="https://github.com/user-attachments/assets/19590ddc-c902-4e15-9b2d-ebe8877963b1">

**Comment by infeo** [comment] 2024-08-23 16:31
I could reproduce the same issue on my test vm. @billziss-gh Can i provide more information, e.g. procmon excerpt or internal log?

**Comment by billziss-gh** [comment] 2024-08-23 17:44
@infeo feel free to add any information that might help us nail this problem.

**Comment by infeo** [comment] 2024-08-24 13:32
I poked around the internet a little bit and stumbled over https://github.com/virtio-win/kvm-guest-drivers-windows/issues/517#issuecomment-1013907916.

Maybe Notepad uses after an update the function [`GetFinalPathNameByHandleW`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfinalpathnamebyhandlew), and since this fails, it cannot save?

**Comment by billziss-gh** [comment] 2024-08-24 23:33
@infeo 

Yes, that was my suspicion, when I saw that the problem only happened when creating local drives, but not when creating global or network drives. This is why I asked for the `subst` test earlier in the thread (which should have failed if the problem was `GetFinalPathNameByHandleW`).

Also this does not explain why I could not reproduce the problem when I tried it on a new VM with latest version of Win11.

----

Perhaps someone can provide me with access to a HyperV VM that exhibits the problem? I would have to be able to run a kernel debugger against it and poke around.

**Comment by infeo** [comment] 2024-08-26 12:36
> Perhaps someone can provide me with access to a HyperV VM that exhibits the problem? I would have to be able to run a kernel debugger against it and poke around.

I'll see, if i can provide one.

In the meantime, here are tow procmon excerpts, one working (because file is saved to C:\Users\User\... and one failing).
[WinFsp_Notepad_Issue.zip](https://github.com/user-attachments/files/16748631/WinFsp_Notepad_Issue.zip)

**Comment by zakels** [comment] 2024-08-27 08:23
> I installed latest version of Windows 11 on a kernel debuggable VM. Unfortunately I am unable to reproduce this.
> 
> <img alt="image" width="642" src="https://private-user-images.githubusercontent.com/15330948/360946952-19590ddc-c902-4e15-9b2d-ebe8877963b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDcwMDcsIm5iZiI6MTcyNDc0NjcwNywicGF0aCI6Ii8xNTMzMDk0OC8zNjA5NDY5NTItMTk1OTBkZGMtYzkwMi00ZTE1LTliMmQtZWJlODg3Nzk2M2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA4MTgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5Njk0YzYwYjY4NGI1ZTA1MGI3MzIwYWQ3ZGJmMjA4ZWMwYWZhN2E0NDFlMzE0NDIyYWMzOTc4ZjE0ZmY1YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nid6SFhhm2AT8yorMIkUSSTYL5tdQMw_qkYOC2jmJG4">

I believe the issue lies upon the app version of notepad, rather than Windows'.
I also wasn't able to reproduce the problem on my newest Windows 11 VM. But once I visited Windows App Store and searched for Notepad. It automatically downloaded 11.2406.9.0 on the VM, and I had the same problem from then on.

**Comment by billziss-gh** [comment] 2024-08-27 17:04
@zakels that is great information. Thank you!

**Comment by k-fim** [comment] 2024-08-28 07:10
> > I installed latest version of Windows 11 on a kernel debuggable VM. Unfortunately I am unable to reproduce this.
> > <img alt="image" width="642" src="https://private-user-images.githubusercontent.com/15330948/360946952-19590ddc-c902-4e15-9b2d-ebe8877963b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDcwMDcsIm5iZiI6MTcyNDc0NjcwNywicGF0aCI6Ii8xNTMzMDk0OC8zNjA5NDY5NTItMTk1OTBkZGMtYzkwMi00ZTE1LTliMmQtZWJlODg3Nzk2M2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA4MTgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5Njk0YzYwYjY4NGI1ZTA1MGI3MzIwYWQ3ZGJmMjA4ZWMwYWZhN2E0NDFlMzE0NDIyYWMzOTc4ZjE0ZmY1YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nid6SFhhm2AT8yorMIkUSSTYL5tdQMw_qkYOC2jmJG4">
> 
> I believe the issue lies upon the app version of notepad, rather than Windows'. I also wasn't able to reproduce the problem on my newest Windows 11 VM. But once I visited Windows App Store and searched for Notepad. It automatically downloaded 11.2406.9.0 on the VM, and I now have the same problem on mine from then on.

version 11.2405.13.0 (previous version of 11.2406.9.0) works great.

**Comment by billziss-gh** [comment] 2024-08-28 13:09
I can confirm this problem. It looks like it happens with latest Notepad from the Microsoft store (11.2406.9.0).

**Comment by billziss-gh** [comment] 2024-08-28 14:33
## Investigation

I believe that @infeo was right when he said that the problem is with `GetFinalPathNameByHandleW`.

I used the WinDbg debugger to attach to the new Windows Notepad, placed a breakpoint on `KERNEL32!GetFinalPathNameByHandleW` and reproduced the problem:

<img width="759" alt="image" src="https://github.com/user-attachments/assets/2c5ca9f7-0a66-486f-97ac-bcf447c7b2a8">

The above screenshot shows the situation after executing the `GetFinalPathNameByHandleW` function. Register `rax` contains the function's return value and the WinDbg `!gle` command reports the error returned from `GetLastError`. As can be seen the function returned `0` and error `ERROR_UNRECOGNIZED_VOLUME`.

This is a known issue with the `GetFinalPathNameByHandleW` API (and some related APIs like `GetVolumePathNameW` AFAICR). Unfortunately it does not seem to work correctly with local (i.e. non-network) drives that are created with the `DefineDosDeviceW` API.

My past investigations of the `GetFinalPathNameByHandleW` API have shown that it can correctly resolve drives in the following situations:

- Network drives, i.e. drives that point to a file system that has a UNC prefix `\\Server\Share` (even though those drives are also created with `DefineDosDeviceW`).

- Global "disk" drives created via the Mount Manager, i.e. drives that are created using the `\\.\X:` syntax when mounting. (The Mount Manager maintains a database of such drives and it seems that `GetFinalPathNameByHandleW` (indirectly) consults the Mount Manager database for such drives.)

Unfortunately local "disk" drives that are created via `DefineDosDeviceW` (and therefore not recorded in the Mount Manager database) are not recognized.

I consider this a long-standing problem (i.e. bug) with `GetFinalPathNameByHandleW` and related APIs. Since `DefineDosDeviceW` is a documented and supported API, drives created via it should work correctly with the rest of the OS. Nevertheless one should be pragmatic and recognize that Microsoft may never fix this problem. This was the primary motivation for adding Mount Manager support to WinFsp in the first place: https://github.com/winfsp/winfsp/issues/182#issuecomment-529265380

## What to Do

Below are some suggestions to tackle this problem:

- Mount your file system as a network file system.
- Mount your file system as a "disk" file system via the Mount Manager. Use `\\.\X:` instead of `X:` when mounting in order to use the Mount Manager. There are some caveats:
    - The Mount Manager requires administrator access. However there is a workaround for this which I have not publicized much for security reasons: you can use the registry setting [`MountUseMountmgrFromFSD`](https://github.com/winfsp/winfsp/wiki/WinFsp-Registry-Settings) (under `HKLM\SOFTWARE\WinFsp`) to circumvent the requirement for Administrator access.
    - Drives created by the Mount Manager are global (i.e. visible to all accounts on the system).

Additionally if someone has a contact with Microsoft that could help with the `GetFinalPathNameByHandleW` API situation, it would be very helpful.

**Comment by d-s-qubeslab** [comment] 2024-08-28 17:23
Thanks @billziss-gh 

I chose to go with Mount Manager, Notepad Save is working, full test by our QA is pending.

We are mounting a virtual folder not a drive, eg. `c:\abc\virtualFolder`

Only code change for me

Old call: `PtfsCreate(0, const_cast<PWSTR>(moutPath.c_str()), 0)`
New call: `PtfsCreate(0, const_cast<PWSTR>((std::wstring(L"\\\\.\\") + moutPath).c_str()), 0)`

Manually set registry to test without requiring admin privilege
`[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\WinFsp]
"MountUseMountmgrFromFSD"=dword:00000001`

Will probably set
`[HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp] "MountUseMountmgrFromFSD"=dword:00000001` also from installer.

**Comment by billziss-gh** [comment] 2024-08-28 17:33
@d-s-qubeslab 

> Will probably set
[HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp] "MountUseMountmgrFromFSD"=dword:00000001 also from installer.

WinFsp uses only the Win32 portion of the registry on a 64-bit system. (This is because WinFsp supports both 64-bit and 32-bit file systems on 64-bit Windows.)

For this reason I recommend against setting the `MountUseMountmgrFromFSD` value in both places. Simply set it next to where the `InstallDir` setting is.

**Comment by d-s-qubeslab** [comment] 2024-08-28 19:58
Got it, Thanks @billziss-gh

**Comment by sschneider** [comment] 2024-09-09 20:38
Looks like the issue is fixed with Windows Editor version 11.2407.8.0

**Closed** 2024-10-05 08:59 UTC
