### ISSUE TITLE
Acrobat Reader DC cannot open PDF on memfs mounted as a directory

### ISSUE THREAD

**Issue by vxgmichel** [winfsp/winfsp#274] opened 2020-01-29 10:59 UTC
## Bug Report

Acrobat Reader DC cannot open a PDF file on a memfs file system when it's mounted as a directory.

It does work when the file system is mounted as a drive. It also works if the 'Protected Mode' of Acrobat Reader is disabled.

It might be a problem with acrobat itself, as suggested in this related issue: #212

### How to Reproduce

- `memfs-x64.exe -m C:\Users\User\memfs-mountpoint`
- Copy a pdf file to `C:\Users\User\memfs-mountpoint`
- Open `C:\Users\User\memfs-mountpoint\pdf.pdf` with Adobe Reader DC
- Observe the dialogue: `There was an error opening this document. Access denied`

This problem does **not** occur if:
- `memfsx64.exe -m R:` is used instead
- or, if the `Enable protected mode at startup` setting of Acrobat Reader is unchecked

### Environment

- OS version and build: _10.0.18363_
- WinFsp version: [1.5.20002](https://github.com/billziss-gh/winfsp/releases/tag/v1.5)

### Logs

Some logs that I gathered:

![acrobat-reader-logs](https://user-images.githubusercontent.com/7490006/70926222-05bb4e80-202d-11ea-9386-c5bdaeb0a683.png)

In particular, those logs seem a bit suspicious:

![reparse](https://user-images.githubusercontent.com/7490006/73270969-104a3580-41e0-11ea-9c5c-f0d6a8431ff8.png)

**Comment by billziss-gh** [comment] 2020-02-06 03:30
The problem appears to be that Acrobat Reader attempts to resolve the junction reparse point on its own, but then gets confused by the NTOS path found in it.

In the FileSpy log below notice that Acrobat Reader issues an `FSCTL_GET_REPARSE_POINT` to NTFS for `mnt` in an attempt to resolve the mount point on its own (i.e. without Windows/NTFS help). Unfortunately it does not appear to be able to handle the resulting path `\Device\Volume{GUID}` (which is a valid NTOS path) and is then unable to construct a proper path to it (it attempts to open `C:\Device\Volume{GUID}\file.pdf` rather than `\\?\GLOBALROOT\Device\Volume{GUID}\file.pdf` that is required for Win32 applications to use NTOS paths directly).

I suspect that we have to contact Adobe directly and make a bug report.

```
939	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_REPARSE	FILE_OPEN CreOpts: 00000021 Access: 00100020 Share:  00000003 Attrib: 0
1171	AcroRd32.exe	IRP_MJ_CREATE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	FILE_OPEN CreOpts: 00000021 Access: 00100020 Share:  00000003 Attrib: 0 Result: FILE_OPENED
2152	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt\DDI0553A_e_armv8m_arm.pdf	STATUS_REPARSE	FILE_OPEN CreOpts: 00400020 Access: 00100080 Share:  00000007 Attrib: 0
2153	AcroRd32.exe	IRP_MJ_CREATE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}\DDI0553A_e_armv8m_arm.pdf	STATUS_SUCCESS	FILE_OPEN CreOpts: 00400020 Access: 00100080 Share:  00000007 Attrib: 0 Result: FILE_OPENED
2154	AcroRd32.exe	FASTIO_QUERY_STANDARD_INFO	\Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}\DDI0553A_e_armv8m_arm.pdf	STATUS_SUCCESS	FileStandardInformation AllocationSize: 00000000-0081E400 EndOfFile: 00000000-0081E2F2 NumberOfLinks: 1 DeletePending: FALSE
2155	AcroRd32.exe	IRP_MJ_CLEANUP	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}\DDI0553A_e_armv8m_arm.pdf	STATUS_SUCCESS	
2156	AcroRd32.exe	IRP_MJ_CLOSE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}\DDI0553A_e_armv8m_arm.pdf	STATUS_SUCCESS	
2157	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt\DDI0553A_e_armv8m_arm.pdf	STATUS_REPARSE	FILE_OPEN CreOpts: 00400020 Access: 00100080 Share:  00000007 Attrib: 0
2158	AcroRd32.exe	IRP_MJ_CREATE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}\DDI0553A_e_armv8m_arm.pdf	STATUS_SUCCESS	FILE_OPEN CreOpts: 00400020 Access: 00100080 Share:  00000007 Attrib: 0 Result: FILE_OPENED
2159	AcroRd32.exe	IRP_MJ_QUERY_INFORMATION	\Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}\DDI0553A_e_armv8m_arm.pdf	STATUS_SUCCESS	FileNameInformation Name: \DDI0553A_e_armv8m_arm.pdf
2160	AcroRd32.exe	IRP_MJ_QUERY_INFORMATION	\Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}\DDI0553A_e_armv8m_arm.pdf	STATUS_SUCCESS	FileNameInformation Name: \DDI0553A_e_armv8m_arm.pdf
2161	AcroRd32.exe	IRP_MJ_CLEANUP	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}\DDI0553A_e_armv8m_arm.pdf	STATUS_SUCCESS	
2162	AcroRd32.exe	IRP_MJ_CLOSE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}\DDI0553A_e_armv8m_arm.pdf	STATUS_SUCCESS	
2163	AcroRd32.exe	FASTIO_QUERY_OPEN		C:\Users\billziss\Desktop\mnt\DDI0553A_e_armv8m_arm.pdf	FAILURE	
2164	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt\DDI0553A_e_armv8m_arm.pdf	STATUS_REPARSE	FILE_OPEN CreOpts: 00200000 Access: 00000080 Share:  00000007 Attrib: 0
2165	AcroRd32.exe	FASTIO_QUERY_OPEN		\Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}\DDI0553A_e_armv8m_arm.pdf	STATUS_SUCCESS	FileNetworkOpenInformation CreateTime: 01D5DC97-4C81131B LastAccTime: 01D5DC97-4C8553DD LastWrtTime: 01D5DC96-DCD2DCE6 ChangeTime: 01D5DC96-DCDB35C2 AllocationSize: 00000000-0081E400 EndOfFile: 00000000-0081E2F2 Attrib: 00000020
2166	AcroRd32.exe	FASTIO_QUERY_OPEN		C:\Users\billziss\Desktop\mnt	FAILURE	
2167	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	FILE_OPEN CreOpts: 00200000 Access: 00000080 Share:  00000007 Attrib: 0 Result: FILE_OPENED
2168	AcroRd32.exe	FASTIO_QUERY_BASIC_INFO		C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	FileBasicInformation CreateTime: 01D5DC97-3BAE39B5 LastAccTime: 01D5DC97-3BAE39B5 LastWrtTime: 01D5DC97-3BAE39B5 ChangeTime: 01D5DC97-43AD1EEC Attrib: 00000410
2169	AcroRd32.exe	IRP_MJ_CLEANUP	                C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	
2170	AcroRd32.exe	IRP_MJ_CLOSE	                C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	
2171	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	FILE_OPEN CreOpts: 00200020 Access: 00100080 Share:  00000007 Attrib: 0 Result: FILE_OPENED
2172	AcroRd32.exe	IRP_MJ_FILE_SYSTEM_CONTROL/IRP_MN_USER_FS_REQUEST	C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	FSCTL_GET_REPARSE_POINT (000900A8)
2173	AcroRd32.exe	IRP_MJ_CLEANUP	                C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	
2174	AcroRd32.exe	IRP_MJ_CLOSE	                C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	
2175	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_FILE_IS_A_DIRECTORY	FILE_OPEN CreOpts: 00000060 Access: 00100080 Share:  00000003 Attrib: 0
2176	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	FILE_OPEN CreOpts: 00200020 Access: 00100080 Share:  00000003 Attrib: 00000080 Result: FILE_OPENED
2177	AcroRd32.exe	IRP_MJ_FILE_SYSTEM_CONTROL/IRP_MN_USER_FS_REQUEST	C:\Users\billziss\Desktop\mnt	STATUS_BUFFER_OVERFLOW	FSCTL_GET_REPARSE_POINT (000900A8)
2178	AcroRd32.exe	IRP_MJ_FILE_SYSTEM_CONTROL/IRP_MN_USER_FS_REQUEST	C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	FSCTL_GET_REPARSE_POINT (000900A8)
2179	AcroRd32.exe	IRP_MJ_CLEANUP	                C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	
2180	AcroRd32.exe	IRP_MJ_CLOSE	                C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	
2181	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_REPARSE	FILE_OPEN CreOpts: 00000020 Access: 00100080 Share:  00000003 Attrib: 0
2182	AcroRd32.exe	IRP_MJ_CREATE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	FILE_OPEN CreOpts: 00000021 Access: 00100080 Share:  00000003 Attrib: 0 Result: FILE_OPENED
2183	AcroRd32.exe	IRP_MJ_CLEANUP	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2184	AcroRd32.exe	IRP_MJ_CLOSE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2185	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_REPARSE	FILE_OPEN CreOpts: 00000010 Access: 00100080 Share:  00000003 Attrib: 0
2199	AcroRd32.exe	IRP_MJ_CREATE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	FILE_OPEN CreOpts: 00000011 Access: 00100080 Share:  00000003 Attrib: 0 Result: FILE_OPENED
2200	AcroRd32.exe	FASTIO_DEVICE_CONTROL		\Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	FAILURE	IOCTL_MOUNTDEV_QUERY_DEVICE_NAME (004D0008)
2201	AcroRd32.exe	IRP_MJ_DEVICE_CONTROL	        \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_INVALID_DEVICE_REQUEST	IOCTL_MOUNTDEV_QUERY_DEVICE_NAME (004D0008)
2202	AcroRd32.exe	IRP_MJ_CLEANUP	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2203	AcroRd32.exe	IRP_MJ_CLOSE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2204	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	FILE_OPEN CreOpts: 00200020 Access: 00100080 Share:  00000003 Attrib: 00000080 Result: FILE_OPENED
2205	AcroRd32.exe	IRP_MJ_FILE_SYSTEM_CONTROL/IRP_MN_USER_FS_REQUEST	C:\Users\billziss\Desktop\mnt	STATUS_BUFFER_OVERFLOW	FSCTL_GET_REPARSE_POINT (000900A8)
2206	AcroRd32.exe	IRP_MJ_FILE_SYSTEM_CONTROL/IRP_MN_USER_FS_REQUEST	C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	FSCTL_GET_REPARSE_POINT (000900A8)
2207	AcroRd32.exe	IRP_MJ_CLEANUP	                C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	
2208	AcroRd32.exe	IRP_MJ_CLOSE	                C:\Users\billziss\Desktop\mnt	STATUS_SUCCESS	
2209	AcroRd32.exe	FASTIO_QUERY_OPEN		C:\Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}\DDI0553A_e_armv8m_arm.pdf	FAILURE	
2210	AcroRd32.exe	IRP_MJ_CREATE	                C:\Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}\DDI0553A_e_armv8m_arm.pdf	STATUS_OBJECT_PATH_NOT_FOUND	FILE_OPEN CreOpts: 00200000 Access: 00000080 Share:  00000007 Attrib: 0
2211	AcroRd32.exe	FASTIO_QUERY_OPEN		C:\Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	FAILURE	
2212	AcroRd32.exe	IRP_MJ_CREATE	                C:\Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_OBJECT_PATH_NOT_FOUND	FILE_OPEN CreOpts: 00200000 Access: 00000080 Share:  00000007 Attrib: 0
2213	AcroRd32.exe	FASTIO_QUERY_OPEN		C:\Device	FAILURE	
2214	AcroRd32.exe	IRP_MJ_CREATE	                C:\Device	STATUS_OBJECT_NAME_NOT_FOUND	FILE_OPEN CreOpts: 00200000 Access: 00000080 Share:  00000007 Attrib: 0
2223	AcroRd32.exe	IRP_MJ_CLEANUP	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2224	AcroRd32.exe	IRP_MJ_CLOSE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2273	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_REPARSE	FILE_OPEN CreOpts: 00000021 Access: 00100020 Share:  00000003 Attrib: 0
2331	AcroRd32.exe	IRP_MJ_CREATE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	FILE_OPEN CreOpts: 00000021 Access: 00100020 Share:  00000003 Attrib: 0 Result: FILE_OPENED
2598	AcroRd32.exe	IRP_MJ_CLEANUP	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2599	AcroRd32.exe	IRP_MJ_CLOSE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2600	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_REPARSE	FILE_OPEN CreOpts: 00000021 Access: 00100020 Share:  00000003 Attrib: 0
2601	AcroRd32.exe	IRP_MJ_CREATE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	FILE_OPEN CreOpts: 00000021 Access: 00100020 Share:  00000003 Attrib: 0 Result: FILE_OPENED
2639	AcroRd32.exe	IRP_MJ_CLEANUP	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2640	AcroRd32.exe	IRP_MJ_CLOSE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2641	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_REPARSE	FILE_OPEN CreOpts: 00000021 Access: 00100020 Share:  00000003 Attrib: 0
2642	AcroRd32.exe	IRP_MJ_CREATE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	FILE_OPEN CreOpts: 00000021 Access: 00100020 Share:  00000003 Attrib: 0 Result: FILE_OPENED
2780	AcroRd32.exe	IRP_MJ_CLEANUP	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2781	AcroRd32.exe	IRP_MJ_CLOSE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2782	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_REPARSE	FILE_OPEN CreOpts: 00000021 Access: 00100020 Share:  00000003 Attrib: 0
2783	AcroRd32.exe	IRP_MJ_CREATE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	FILE_OPEN CreOpts: 00000021 Access: 00100020 Share:  00000003 Attrib: 0 Result: FILE_OPENED
2787	AcroRd32.exe	IRP_MJ_CLEANUP	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2788	AcroRd32.exe	IRP_MJ_CLOSE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	
2789	AcroRd32.exe	IRP_MJ_CREATE	                C:\Users\billziss\Desktop\mnt	STATUS_REPARSE	FILE_OPEN CreOpts: 00000021 Access: 00100020 Share:  00000003 Attrib: 0
2790	AcroRd32.exe	IRP_MJ_CREATE	                \Device\Volume{9cff1b29-6167-11e9-bcff-080027371f8e}	STATUS_SUCCESS	FILE_OPEN CreOpts: 00000021 Access: 00100020 Share:  00000003 Attrib: 0 Result: FILE_OPENED
```

**Comment by vxgmichel** [comment] 2020-02-06 12:04
> I suspect that we have to contact Adobe and make a bug report.

Well, Adobe doesn't seem too talkative when it comes to this particular problem:

- Same issue with a USB drive mounted as a directory (2017 - no answer)
  https://community.adobe.com/t5/acrobat-reader/quot-access-denied-quot-opening-pdfs-inside-mount-points/m-p/9004849?page=1

- Same issue (2018 - some answers from the devteam then ignored)
  https://community.adobe.com/t5/acrobat-reader/there-was-an-error-opening-this-document-access-denied/m-p/9597315?page=1

- Same issue with Dokan and NTFS (2018 - no answer):
  https://community.adobe.com/t5/acrobat-reader/opening-and-saving-files-in-protected-mode-on-ntfs-mount-point/m-p/9682712?page=1

- Same issue with CBFS Connect (2019 - no answer)
  https://community.adobe.com/t5/acrobat-reader/adobe-acrobat-reader-fails-to-open-a-pdf-file-on-a-user-mode-file-system/m-p/10536354?page=1

For the record, dokany has the same unresolved issue on its tracker: https://github.com/dokan-dev/dokany/issues/640

**Comment by billziss-gh** [comment] 2020-02-06 18:43
I have found a uservoice form here:

https://acrobat.uservoice.com/forums/926812

I will write something up and hopefully they will respond.

**Comment by billziss-gh** [comment] 2020-02-06 23:29
I have posted a bug report on the uservoice forum. If you are interested in seeing this problem resolved, please consider upvoting the submission.

**Comment by alonsohki** [comment] 2021-01-07 11:19
Still no response from Adobe after almost one year, despite being this report the most voted one on the site. It seems that we would need to push a bit harder to get this done.

**Comment by billziss-gh** [comment] 2021-01-07 17:36
In my experience the best way to move things forward in such cases is to know someone inside the organization. Unfortunately I do not know anyone in Adobe.

**Comment by Lnd-stoL** [comment] 2021-02-10 09:03
I ran into the exactly the same issue with Acrobat Reader (not being able to open a file with "Permission denied" error message) but with memfs mounted as drive, not as a directory. 
The reproduction steps in my case are the same except for mounting memfs as a drive (memfsx64.exe -m R:).
I have tested this with the latest stable WinFSP version (2020.2) and latest available Acrobat reader (21.001.20135). I'm not sure my case is related to the issue. If not I can definitely open a new one.

**Comment by khambrecht** [comment] 2021-02-22 15:54
as per latest comment in [1] from Feb. 14th, it looks like Adobe is willing to take care.

[1] https://acrobat.uservoice.com/forums/926812-acrobat-reader-for-windows-and-mac/suggestions/39652114-acrobat-reader-unable-to-access-files-via-junction

**Comment by billziss-gh** [comment] 2021-11-18 16:39
Has there be any update from Adobe on this?

**Comment by billziss-gh** [comment] 2022-06-15 10:18
Closing this as it appears to have been rectified by Adobe. Thank you to the Adobe folks for resolving the issue.

**Closed by billziss-gh** 2022-06-15 10:18 UTC

**Comment by cetetesoft** [comment] 2023-08-01 17:37
The issue still persists for file paths containing non-ASCII characters such as accents. For example, while I can open "e.pdf" I cannot open "é.pdf" unless I turn off Protected Mode.
BTW, does anyone know the Proctected Mode log file location?

**Comment by vxgmichel** [comment] 2023-08-02 09:23
> The issue still persists for file paths containing non-ASCII characters such as accents. For example, while I can open "e.pdf" I cannot open "é.pdf" unless I turn off Protected Mode.

I could not replicate this behavior with:
- Acrobat Reader version 2023.003.20201
- Winfsp 1.12.22339 and Winfsp 2.0.23075
- A memfs in `C:\Users\User\Desktop\test`
- A `Café.pdf` file

**Comment by cetetesoft** [comment] 2023-08-02 18:07
You're right, sorry. It's working fine with memfs. However I get this error when using an application I'm working on, created in Go with `winfsp/cgofuse`. The `memfs.go` example provided isn't affected either, so it's definitely a problem of mine.

**Comment by cetetesoft** [comment] 2023-08-02 19:10
After a few tests, I've found out setting the `FSP_FUSE_CAP_CASE_INSENSITIVE` flag to be the cause.
Acrobat can no longer open the file by just adding this line to `memfs.go` before mounting:
`host.SetCapReaddirPlus(true)`
